@startuml Shop
title Team 3

skinparam componentStyle uml2
skinparam packageStyle rectangle

' ================
'  PACKAGES
' ================

package "Client" {
  actor Kunde as User
}

package "Order- & Integrations-Plattform (REST)" {
  component "Order-/Orchestrator Service" as ORCH
}

package "Backend Services" {
  component "Inventory Service (gRPC)" as INV
  component "Payment Service (REST)" as PAY
  component "Warehouse Service\n(AMQP Consumer)" as WMS
}

package "Messaging" {
  queue "RabbitMQ" as MQ
}

package "Logging" {
  component "Logging Service\n(HTTP POST)" as LOG
}

' ================
'  MAIN PROCESS FLOW
' ================

User --> ORCH : 1. Bestellung senden (REST /process-order)

' Inventory
ORCH --> INV : 2. Bestand prüfen (gRPC)
INV --> ORCH : 3. Prüfergebnis (Items-Status)

' Payment
ORCH --> PAY : 4. Zahlung durchführen (REST)
PAY --> ORCH : 5. Zahlungsergebnis (orderId, paymentStatus)

' Publish to MQ
ORCH --> MQ : 6. Versandauftrag publish (AMQP)
MQ --> WMS : 7. Versandauftrag empfangen (consume)

' ================
'  LOGGING-FLUSS
' ================

' Alle Services schicken Logs an Logging-Service (HTTP POST)
ORCH --> LOG : Log(Event)
INV --> LOG : Log(Event)
PAY --> LOG : Log(Event)
WMS --> LOG : Log(Event)

@enduml
